on: workflow_dispatch
jobs:
  http:
    runs-on: ubuntu-26.04
    permissions:
      actions: write
    steps:
      - run: |
          CPU=$(lscpu)
          echo $CPU
          LOCATION=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2017-04-02&format=text")
          if [[ $CPU != *'BogoMIPS'* || $LOCATION != westus2 ]]; then
              gh workflow run "${{ github.workflow }}" -R "${{ github.repository }}"
              exit 1
          fi
          sudo apt-get install -y traceroute
          curl -w "Пинг (задержка до Владивостока): %{time_connect} секунд\n" -s -o /dev/null https://vvsu.ru
          sudo traceroute -T -p 443 vvsu.ru
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
