on: workflow_dispatch
jobs:
  http:
    runs-on: ubuntu-26.04
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v7
      - run: |
          pip install aiogram google-generativeai
          python main.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
