on: workflow_dispatch
jobs:
  vpn:
    runs-on: ubuntu-24.04-arm
    permissions:
      actions: write
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LOCATION=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2017-04-02&format=text")
          if [[ $LOCATION != eastus2 ]]; then
              gh workflow run "$GITHUB_WORKFLOW" --repo "$GITHUB_REPOSITORY" --ref "$GITHUB_REF_NAME"
              exit 1
          fi
          sudo apt-get update
          sudo apt-get install -y mtr hping3 curl
          sudo mtr --tcp --port 443 -r -w -c 5 tiktok.com
          sudo hping3 -S -p 443 -c 4 tiktok.com
          curl -w "DNS: %{time_namelookup}s\nTCP Установка (RTT): %{time_connect}s\nTLS Шифрование: %{time_appconnect}s\nОбщее время: %{time_total}s\n" -o /dev/null -s https://core.telegram.org
      - env:
          TS_KEY: ${{ secrets.TAILSCALE_KEY }}
        run: |
          lscpu
          exit 1
          curl -fsSL https://tailscale.com/install.sh | sh
          echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
          echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
          sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
          NETDEV=$(ip -o route get 8.8.8.8 | cut -f 5 -d " ")
          sudo ethtool -K $NETDEV rx-udp-gro-forwarding on rx-gro-list off
          sudo tailscale up --authkey=$TS_KEY
          sleep 5
          sudo tailscale set --exit-node=east-us
          
          wget -q https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-aarch64.tgz
          tar -xzf ookla-speedtest-1.2.0-linux-aarch64.tgz
          ./speedtest --accept-license --accept-gdpr
