on: workflow_dispatch
jobs:
  vpn:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LOCATION=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2017-04-02&format=text")
          if [[ $LOCATION != eastus ]]; then
              gh workflow run "$GITHUB_WORKFLOW" --repo "$GITHUB_REPOSITORY" --ref "$GITHUB_REF_NAME"
              exit 1
          fi

      - env:
          TS_KEY: ${{ secrets.TAILSCALE_KEY }}
        run: |
          wget -q https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
          tar -xzf ookla-speedtest-1.2.0-linux-x86_64.tgz
          ./speedtest --accept-license --accept-gdpr
