on:
  workflow_dispatch:
  schedule:
    - cron: 43 */3 * * *
jobs:
  vpn:
    runs-on: ubuntu-26.04-arm
    permissions:
      actions: write
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
          SESSION: ${{ secrets.SESSION }}
          TAILSCALE: ${{ secrets.TAILSCALE }}
        run: |
          LOCATION=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2017-04-02&format=text")
          if [[ ${LOCATION,,} != eastus ]]; then
              gh workflow run "$GITHUB_WORKFLOW" --repo "$GITHUB_REPOSITORY" --ref "$GITHUB_REF_NAME"
              exit 1
          fi
          wget https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-aarch64.tgz
          tar xzf ookla-speedtest-1.2.0-linux-aarch64.tgz speedtest && ./speedtest --accept-license --accept-gdpr
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo systemctl stop tailscaled
          echo "$SESSION" | sudo tee /var/lib/tailscale/tailscaled.state
          sudo systemctl start tailscaled
          echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
          echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
          sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
          NETDEV=$(ip -o route get 8.8.8.8 | cut -f 5 -d " ")
          sudo ethtool -K $NETDEV rx-udp-gro-forwarding on rx-gro-list off
          sudo tailscale up --advertise-exit-node --auth-key $TAILSCALE --hostname east-us --ssh
          sudo apt-get install -y dstat
          dstat 60
#while true; do sudo tailscale status --active --header; sleep 60; done
