on:
  workflow_dispatch:
  schedule:
    - cron: 43 */3 * * *
jobs:
  vpn:
    runs-on: ubuntu-26.04
    permissions:
      actions: write
    steps:
      - run: |
          LOCATION=$(curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2017-04-02&format=text")
          if [[ $LOCATION != eastus ]]; then
              gh workflow run "${{ github.workflow }}" -R "${{ github.repository }}"
              exit 1
          fi
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo systemctl stop tailscaled
          echo "$SESSION" | sudo tee /var/lib/tailscale/tailscaled.state
          sudo systemctl start tailscaled
          sudo tailscale up --advertise-exit-node --auth-key $TAILSCALE --hostname east-us --ssh
          while true; do sudo tailscale status --active --header; sleep 60; done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SESSION: ${{ secrets.SESSION }}
          TAILSCALE: ${{ secrets.TAILSCALE }}
